/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'overdueTasks' : bigint,
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'pendingTasks' : bigint,
}
export interface Goal {
  'id' : string,
  'status' : GoalStatus,
  'title' : string,
  'description' : string,
  'progress' : bigint,
  'targetDate' : [] | [string],
  'notes' : string,
  'category' : GoalCategory,
}
export type GoalCategory = { 'other' : null } |
  { 'learning' : null } |
  { 'work' : null } |
  { 'personal' : null } |
  { 'health' : null };
export type GoalStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'paused' : null };
export interface JournalEntry {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : string,
  'mood' : JournalMood,
  'createdAt' : string,
  'tags' : Array<string>,
}
export type JournalMood = { 'sad' : null } |
  { 'happy' : null } |
  { 'energized' : null } |
  { 'stressed' : null } |
  { 'neutral' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Project { 'id' : string, 'name' : string, 'color' : string }
export interface Task {
  'id' : string,
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [string],
  'description' : string,
  'projectId' : [] | [string],
  'notes' : string,
  'priority' : Priority,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGoal' : ActorMethod<
    [string, string, string, GoalCategory, [] | [string], string],
    undefined
  >,
  'createJournalEntry' : ActorMethod<
    [string, string, string, JournalMood, Array<string>, string, string],
    undefined
  >,
  'createProject' : ActorMethod<[string, string, string], undefined>,
  'createTask' : ActorMethod<
    [string, string, string, Priority, [] | [string], string, [] | [string]],
    undefined
  >,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'deleteJournalEntry' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getAllGoals' : ActorMethod<[], Array<Goal>>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getTasksByCompletion' : ActorMethod<[boolean], Array<Task>>,
  'getTasksByProject' : ActorMethod<[string], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTasks' : ActorMethod<[string], Array<Task>>,
  'toggleTaskCompletion' : ActorMethod<[string], undefined>,
  'updateGoal' : ActorMethod<
    [
      string,
      string,
      string,
      GoalCategory,
      [] | [string],
      GoalStatus,
      bigint,
      string,
    ],
    undefined
  >,
  'updateJournalEntry' : ActorMethod<
    [string, string, string, JournalMood, Array<string>, string, string],
    undefined
  >,
  'updateProject' : ActorMethod<[string, string, string], undefined>,
  'updateTask' : ActorMethod<
    [string, string, string, Priority, [] | [string], string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];