/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GoalCategory = IDL.Variant({
  'other' : IDL.Null,
  'learning' : IDL.Null,
  'work' : IDL.Null,
  'personal' : IDL.Null,
  'health' : IDL.Null,
});
export const JournalMood = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'energized' : IDL.Null,
  'stressed' : IDL.Null,
  'neutral' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const GoalStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'paused' : IDL.Null,
});
export const Goal = IDL.Record({
  'id' : IDL.Text,
  'status' : GoalStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'targetDate' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'category' : GoalCategory,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'mood' : JournalMood,
  'createdAt' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'priority' : Priority,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardSummary = IDL.Record({
  'overdueTasks' : IDL.Nat,
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'pendingTasks' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGoal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, GoalCategory, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'createJournalEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JournalMood,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Priority,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getTasksByCompletion' : IDL.Func([IDL.Bool], [IDL.Vec(Task)], ['query']),
  'getTasksByProject' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'toggleTaskCompletion' : IDL.Func([IDL.Text], [], []),
  'updateGoal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        GoalCategory,
        IDL.Opt(IDL.Text),
        GoalStatus,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateJournalEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JournalMood,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Priority,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GoalCategory = IDL.Variant({
    'other' : IDL.Null,
    'learning' : IDL.Null,
    'work' : IDL.Null,
    'personal' : IDL.Null,
    'health' : IDL.Null,
  });
  const JournalMood = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'energized' : IDL.Null,
    'stressed' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const GoalStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'paused' : IDL.Null,
  });
  const Goal = IDL.Record({
    'id' : IDL.Text,
    'status' : GoalStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'targetDate' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'category' : GoalCategory,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'mood' : JournalMood,
    'createdAt' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'priority' : Priority,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardSummary = IDL.Record({
    'overdueTasks' : IDL.Nat,
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'pendingTasks' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGoal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          GoalCategory,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createJournalEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JournalMood,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Priority,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getTasksByCompletion' : IDL.Func([IDL.Bool], [IDL.Vec(Task)], ['query']),
    'getTasksByProject' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'toggleTaskCompletion' : IDL.Func([IDL.Text], [], []),
    'updateGoal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          GoalCategory,
          IDL.Opt(IDL.Text),
          GoalStatus,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateJournalEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JournalMood,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Priority,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };