/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DashboardSummary {
    overdueTasks: bigint;
    totalTasks: bigint;
    completedTasks: bigint;
    pendingTasks: bigint;
}
export interface JournalEntry {
    id: string;
    title: string;
    content: string;
    date: string;
    mood: JournalMood;
    createdAt: string;
    tags: Array<string>;
}
export interface Task {
    id: string;
    title: string;
    completed: boolean;
    dueDate?: string;
    description: string;
    projectId?: string;
    notes: string;
    priority: Priority;
}
export interface Project {
    id: string;
    name: string;
    color: string;
}
export interface UserProfile {
    name: string;
}
export interface Goal {
    id: string;
    status: GoalStatus;
    title: string;
    description: string;
    progress: bigint;
    targetDate?: string;
    notes: string;
    category: GoalCategory;
}
export enum GoalCategory {
    other = "other",
    learning = "learning",
    work = "work",
    personal = "personal",
    health = "health"
}
export enum GoalStatus {
    active = "active",
    completed = "completed",
    paused = "paused"
}
export enum JournalMood {
    sad = "sad",
    happy = "happy",
    energized = "energized",
    stressed = "stressed",
    neutral = "neutral"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGoal(id: string, title: string, description: string, category: GoalCategory, targetDate: string | null, notes: string): Promise<void>;
    createJournalEntry(id: string, title: string, content: string, mood: JournalMood, tags: Array<string>, date: string, createdAt: string): Promise<void>;
    createProject(id: string, name: string, color: string): Promise<void>;
    createTask(id: string, title: string, desc: string, priority: Priority, dueDate: string | null, notes: string, projectId: string | null): Promise<void>;
    deleteGoal(goalId: string): Promise<void>;
    deleteJournalEntry(entryId: string): Promise<void>;
    deleteProject(projectId: string): Promise<void>;
    deleteTask(taskId: string): Promise<void>;
    getAllGoals(): Promise<Array<Goal>>;
    getAllJournalEntries(): Promise<Array<JournalEntry>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllTasks(): Promise<Array<Task>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getTasksByCompletion(isCompleted: boolean): Promise<Array<Task>>;
    getTasksByProject(projectId: string): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTasks(searchTerm: string): Promise<Array<Task>>;
    toggleTaskCompletion(taskId: string): Promise<void>;
    updateGoal(id: string, title: string, description: string, category: GoalCategory, targetDate: string | null, status: GoalStatus, progress: bigint, notes: string): Promise<void>;
    updateJournalEntry(id: string, title: string, content: string, mood: JournalMood, tags: Array<string>, date: string, createdAt: string): Promise<void>;
    updateProject(id: string, name: string, color: string): Promise<void>;
    updateTask(id: string, title: string, desc: string, priority: Priority, dueDate: string | null, notes: string, projectId: string | null): Promise<void>;
}
import type { Goal as _Goal, GoalCategory as _GoalCategory, GoalStatus as _GoalStatus, JournalEntry as _JournalEntry, JournalMood as _JournalMood, Priority as _Priority, Task as _Task, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGoal(arg0: string, arg1: string, arg2: string, arg3: GoalCategory, arg4: string | null, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, arg2, to_candid_GoalCategory_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, arg2, to_candid_GoalCategory_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async createJournalEntry(arg0: string, arg1: string, arg2: string, arg3: JournalMood, arg4: Array<string>, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createJournalEntry(arg0, arg1, arg2, to_candid_JournalMood_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJournalEntry(arg0, arg1, arg2, to_candid_JournalMood_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async createProject(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, arg2);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: string, arg3: Priority, arg4: string | null, arg5: string, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_Priority_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, to_candid_Priority_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteGoal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async deleteJournalEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllGoals(): Promise<Array<Goal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGoals();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGoals();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalEntries();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalEntries();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getTasksByCompletion(arg0: boolean): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByCompletion(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByCompletion(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByProject(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByProject(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByProject(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchTasks(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTasks(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTasks(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleTaskCompletion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskCompletion(arg0);
            return result;
        }
    }
    async updateGoal(arg0: string, arg1: string, arg2: string, arg3: GoalCategory, arg4: string | null, arg5: GoalStatus, arg6: bigint, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0, arg1, arg2, to_candid_GoalCategory_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_GoalStatus_n31(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0, arg1, arg2, to_candid_GoalCategory_n3(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_GoalStatus_n31(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async updateJournalEntry(arg0: string, arg1: string, arg2: string, arg3: JournalMood, arg4: Array<string>, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalEntry(arg0, arg1, arg2, to_candid_JournalMood_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalEntry(arg0, arg1, arg2, to_candid_JournalMood_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async updateProject(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTask(arg0: string, arg1: string, arg2: string, arg3: Priority, arg4: string | null, arg5: string, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_Priority_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_Priority_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_GoalCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalCategory): GoalCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_GoalStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalStatus): GoalStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_JournalEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalEntry): JournalEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_JournalMood_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalMood): JournalMood {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _GoalStatus;
    title: string;
    description: string;
    progress: bigint;
    targetDate: [] | [string];
    notes: string;
    category: _GoalCategory;
}): {
    id: string;
    status: GoalStatus;
    title: string;
    description: string;
    progress: bigint;
    targetDate?: string;
    notes: string;
    category: GoalCategory;
} {
    return {
        id: value.id,
        status: from_candid_GoalStatus_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        progress: value.progress,
        targetDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.targetDate)),
        notes: value.notes,
        category: from_candid_GoalCategory_n16(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    date: string;
    mood: _JournalMood;
    createdAt: string;
    tags: Array<string>;
}): {
    id: string;
    title: string;
    content: string;
    date: string;
    mood: JournalMood;
    createdAt: string;
    tags: Array<string>;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        mood: from_candid_JournalMood_n21(_uploadFile, _downloadFile, value.mood),
        createdAt: value.createdAt,
        tags: value.tags
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    completed: boolean;
    dueDate: [] | [string];
    description: string;
    projectId: [] | [string];
    notes: string;
    priority: _Priority;
}): {
    id: string;
    title: string;
    completed: boolean;
    dueDate?: string;
    description: string;
    projectId?: string;
    notes: string;
    priority: Priority;
} {
    return {
        id: value.id,
        title: value.title,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        projectId: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.projectId)),
        notes: value.notes,
        priority: from_candid_Priority_n26(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    paused: null;
}): GoalStatus {
    return "active" in value ? GoalStatus.active : "completed" in value ? GoalStatus.completed : "paused" in value ? GoalStatus.paused : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    learning: null;
} | {
    work: null;
} | {
    personal: null;
} | {
    health: null;
}): GoalCategory {
    return "other" in value ? GoalCategory.other : "learning" in value ? GoalCategory.learning : "work" in value ? GoalCategory.work : "personal" in value ? GoalCategory.personal : "health" in value ? GoalCategory.health : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    happy: null;
} | {
    energized: null;
} | {
    stressed: null;
} | {
    neutral: null;
}): JournalMood {
    return "sad" in value ? JournalMood.sad : "happy" in value ? JournalMood.happy : "energized" in value ? JournalMood.energized : "stressed" in value ? JournalMood.stressed : "neutral" in value ? JournalMood.neutral : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalEntry>): Array<JournalEntry> {
    return value.map((x)=>from_candid_JournalEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n24(_uploadFile, _downloadFile, x));
}
function to_candid_GoalCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): _GoalCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_GoalStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalStatus): _GoalStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_JournalMood_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JournalMood): _JournalMood {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalStatus): {
    active: null;
} | {
    completed: null;
} | {
    paused: null;
} {
    return value == GoalStatus.active ? {
        active: null
    } : value == GoalStatus.completed ? {
        completed: null
    } : value == GoalStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): {
    other: null;
} | {
    learning: null;
} | {
    work: null;
} | {
    personal: null;
} | {
    health: null;
} {
    return value == GoalCategory.other ? {
        other: null
    } : value == GoalCategory.learning ? {
        learning: null
    } : value == GoalCategory.work ? {
        work: null
    } : value == GoalCategory.personal ? {
        personal: null
    } : value == GoalCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JournalMood): {
    sad: null;
} | {
    happy: null;
} | {
    energized: null;
} | {
    stressed: null;
} | {
    neutral: null;
} {
    return value == JournalMood.sad ? {
        sad: null
    } : value == JournalMood.happy ? {
        happy: null
    } : value == JournalMood.energized ? {
        energized: null
    } : value == JournalMood.stressed ? {
        stressed: null
    } : value == JournalMood.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
